sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: yk20010326

  redis:
    host: 127.0.0.1
    port: 6379
    database: 10

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tDgkTr8Ldu4BYrqndqU
    access-key-secret: TYS5VwM5cgMLjNZq72dQSYJUdqv70Y
    bucket-name: yangkai999